spring:
  application:
    name: spring-security
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/Documents/h2/ssong
    username: ssong
    password: 1234
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: admin
      password: 1
  output:
    ansi:
      enabled: always

server:
  port: 80
  error:
    include-message: always
logging:
  level:
    org:
      springframework: info
      hibernate:
        type:
          descriptor:
            sql: trace


decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true